// <auto-generated />
namespace WebApp.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class rename_appointments_numberphone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rename_appointments_numberphone));
        
        string IMigrationMetadata.Id
        {
            get { return "201910180923093_rename_appointments_numberphone"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
